// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppApp app app
//
// swagger:model app.App
type AppApp struct {

	// app sandbox
	AppSandbox *AppAppSandbox `json:"app_sandbox,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// installers
	Installers []*AppAppInstaller `json:"installers"`

	// name
	Name string `json:"name,omitempty"`

	// org id
	OrgID string `json:"org_id,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// status description
	StatusDescription string `json:"status_description,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this app app
func (m *AppApp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppSandbox(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstallers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppApp) validateAppSandbox(formats strfmt.Registry) error {
	if swag.IsZero(m.AppSandbox) { // not required
		return nil
	}

	if m.AppSandbox != nil {
		if err := m.AppSandbox.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("app_sandbox")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("app_sandbox")
			}
			return err
		}
	}

	return nil
}

func (m *AppApp) validateInstallers(formats strfmt.Registry) error {
	if swag.IsZero(m.Installers) { // not required
		return nil
	}

	for i := 0; i < len(m.Installers); i++ {
		if swag.IsZero(m.Installers[i]) { // not required
			continue
		}

		if m.Installers[i] != nil {
			if err := m.Installers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("installers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("installers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this app app based on the context it is used
func (m *AppApp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAppSandbox(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstallers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppApp) contextValidateAppSandbox(ctx context.Context, formats strfmt.Registry) error {

	if m.AppSandbox != nil {

		if swag.IsZero(m.AppSandbox) { // not required
			return nil
		}

		if err := m.AppSandbox.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("app_sandbox")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("app_sandbox")
			}
			return err
		}
	}

	return nil
}

func (m *AppApp) contextValidateInstallers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Installers); i++ {

		if m.Installers[i] != nil {

			if swag.IsZero(m.Installers[i]) { // not required
				return nil
			}

			if err := m.Installers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("installers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("installers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppApp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppApp) UnmarshalBinary(b []byte) error {
	var res AppApp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
