// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetInstallEventsParams creates a new GetInstallEventsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstallEventsParams() *GetInstallEventsParams {
	return &GetInstallEventsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstallEventsParamsWithTimeout creates a new GetInstallEventsParams object
// with the ability to set a timeout on a request.
func NewGetInstallEventsParamsWithTimeout(timeout time.Duration) *GetInstallEventsParams {
	return &GetInstallEventsParams{
		timeout: timeout,
	}
}

// NewGetInstallEventsParamsWithContext creates a new GetInstallEventsParams object
// with the ability to set a context for a request.
func NewGetInstallEventsParamsWithContext(ctx context.Context) *GetInstallEventsParams {
	return &GetInstallEventsParams{
		Context: ctx,
	}
}

// NewGetInstallEventsParamsWithHTTPClient creates a new GetInstallEventsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstallEventsParamsWithHTTPClient(client *http.Client) *GetInstallEventsParams {
	return &GetInstallEventsParams{
		HTTPClient: client,
	}
}

/*
GetInstallEventsParams contains all the parameters to send to the API endpoint

	for the get install events operation.

	Typically these are written to a http.Request.
*/
type GetInstallEventsParams struct {

	/* InstallID.

	   install ID
	*/
	InstallID string

	/* Limit.

	   limit of results to return

	   Default: 10
	*/
	Limit *int64

	/* Offset.

	   offset of results to return
	*/
	Offset *int64

	/* XNuonPaginationEnabled.

	   Enable pagination
	*/
	XNuonPaginationEnabled *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get install events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallEventsParams) WithDefaults() *GetInstallEventsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get install events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallEventsParams) SetDefaults() {
	var (
		limitDefault = int64(10)

		offsetDefault = int64(0)
	)

	val := GetInstallEventsParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get install events params
func (o *GetInstallEventsParams) WithTimeout(timeout time.Duration) *GetInstallEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get install events params
func (o *GetInstallEventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get install events params
func (o *GetInstallEventsParams) WithContext(ctx context.Context) *GetInstallEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get install events params
func (o *GetInstallEventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get install events params
func (o *GetInstallEventsParams) WithHTTPClient(client *http.Client) *GetInstallEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get install events params
func (o *GetInstallEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the get install events params
func (o *GetInstallEventsParams) WithInstallID(installID string) *GetInstallEventsParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the get install events params
func (o *GetInstallEventsParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WithLimit adds the limit to the get install events params
func (o *GetInstallEventsParams) WithLimit(limit *int64) *GetInstallEventsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get install events params
func (o *GetInstallEventsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get install events params
func (o *GetInstallEventsParams) WithOffset(offset *int64) *GetInstallEventsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get install events params
func (o *GetInstallEventsParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithXNuonPaginationEnabled adds the xNuonPaginationEnabled to the get install events params
func (o *GetInstallEventsParams) WithXNuonPaginationEnabled(xNuonPaginationEnabled *bool) *GetInstallEventsParams {
	o.SetXNuonPaginationEnabled(xNuonPaginationEnabled)
	return o
}

// SetXNuonPaginationEnabled adds the xNuonPaginationEnabled to the get install events params
func (o *GetInstallEventsParams) SetXNuonPaginationEnabled(xNuonPaginationEnabled *bool) {
	o.XNuonPaginationEnabled = xNuonPaginationEnabled
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstallEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.XNuonPaginationEnabled != nil {

		// header param x-nuon-pagination-enabled
		if err := r.SetHeaderParam("x-nuon-pagination-enabled", swag.FormatBool(*o.XNuonPaginationEnabled)); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
