// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon-go/models"
)

// NewInstallerCreateInstallParams creates a new InstallerCreateInstallParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInstallerCreateInstallParams() *InstallerCreateInstallParams {
	return &InstallerCreateInstallParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInstallerCreateInstallParamsWithTimeout creates a new InstallerCreateInstallParams object
// with the ability to set a timeout on a request.
func NewInstallerCreateInstallParamsWithTimeout(timeout time.Duration) *InstallerCreateInstallParams {
	return &InstallerCreateInstallParams{
		timeout: timeout,
	}
}

// NewInstallerCreateInstallParamsWithContext creates a new InstallerCreateInstallParams object
// with the ability to set a context for a request.
func NewInstallerCreateInstallParamsWithContext(ctx context.Context) *InstallerCreateInstallParams {
	return &InstallerCreateInstallParams{
		Context: ctx,
	}
}

// NewInstallerCreateInstallParamsWithHTTPClient creates a new InstallerCreateInstallParams object
// with the ability to set a custom HTTPClient for a request.
func NewInstallerCreateInstallParamsWithHTTPClient(client *http.Client) *InstallerCreateInstallParams {
	return &InstallerCreateInstallParams{
		HTTPClient: client,
	}
}

/*
InstallerCreateInstallParams contains all the parameters to send to the API endpoint

	for the installer create install operation.

	Typically these are written to a http.Request.
*/
type InstallerCreateInstallParams struct {

	/* InstallerSlug.

	   installer slug or ID
	*/
	InstallerSlug string

	/* Req.

	   Input
	*/
	Req *models.ServiceCreateInstallRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the installer create install params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InstallerCreateInstallParams) WithDefaults() *InstallerCreateInstallParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the installer create install params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InstallerCreateInstallParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the installer create install params
func (o *InstallerCreateInstallParams) WithTimeout(timeout time.Duration) *InstallerCreateInstallParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the installer create install params
func (o *InstallerCreateInstallParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the installer create install params
func (o *InstallerCreateInstallParams) WithContext(ctx context.Context) *InstallerCreateInstallParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the installer create install params
func (o *InstallerCreateInstallParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the installer create install params
func (o *InstallerCreateInstallParams) WithHTTPClient(client *http.Client) *InstallerCreateInstallParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the installer create install params
func (o *InstallerCreateInstallParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallerSlug adds the installerSlug to the installer create install params
func (o *InstallerCreateInstallParams) WithInstallerSlug(installerSlug string) *InstallerCreateInstallParams {
	o.SetInstallerSlug(installerSlug)
	return o
}

// SetInstallerSlug adds the installerSlug to the installer create install params
func (o *InstallerCreateInstallParams) SetInstallerSlug(installerSlug string) {
	o.InstallerSlug = installerSlug
}

// WithReq adds the req to the installer create install params
func (o *InstallerCreateInstallParams) WithReq(req *models.ServiceCreateInstallRequest) *InstallerCreateInstallParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the installer create install params
func (o *InstallerCreateInstallParams) SetReq(req *models.ServiceCreateInstallRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *InstallerCreateInstallParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param installer_slug
	if err := r.SetPathParam("installer_slug", o.InstallerSlug); err != nil {
		return err
	}
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
