// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon-go/models"
)

// CreateWorkflowStepApprovalResponseReader is a Reader for the CreateWorkflowStepApprovalResponse structure.
type CreateWorkflowStepApprovalResponseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateWorkflowStepApprovalResponseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewCreateWorkflowStepApprovalResponseCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateWorkflowStepApprovalResponseBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateWorkflowStepApprovalResponseUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateWorkflowStepApprovalResponseForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateWorkflowStepApprovalResponseNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateWorkflowStepApprovalResponseInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response] CreateWorkflowStepApprovalResponse", response, response.Code())
	}
}

// NewCreateWorkflowStepApprovalResponseCreated creates a CreateWorkflowStepApprovalResponseCreated with default headers values
func NewCreateWorkflowStepApprovalResponseCreated() *CreateWorkflowStepApprovalResponseCreated {
	return &CreateWorkflowStepApprovalResponseCreated{}
}

/*
CreateWorkflowStepApprovalResponseCreated describes a response with status code 201, with default header values.

Created
*/
type CreateWorkflowStepApprovalResponseCreated struct {
	Payload *models.ServiceCreateWorkflowStepApprovalResponseResponse
}

// IsSuccess returns true when this create workflow step approval response created response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create workflow step approval response created response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response created response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create workflow step approval response created response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create workflow step approval response created response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create workflow step approval response created response
func (o *CreateWorkflowStepApprovalResponseCreated) Code() int {
	return 201
}

func (o *CreateWorkflowStepApprovalResponseCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseCreated %s", 201, payload)
}

func (o *CreateWorkflowStepApprovalResponseCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseCreated %s", 201, payload)
}

func (o *CreateWorkflowStepApprovalResponseCreated) GetPayload() *models.ServiceCreateWorkflowStepApprovalResponseResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceCreateWorkflowStepApprovalResponseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateWorkflowStepApprovalResponseBadRequest creates a CreateWorkflowStepApprovalResponseBadRequest with default headers values
func NewCreateWorkflowStepApprovalResponseBadRequest() *CreateWorkflowStepApprovalResponseBadRequest {
	return &CreateWorkflowStepApprovalResponseBadRequest{}
}

/*
CreateWorkflowStepApprovalResponseBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateWorkflowStepApprovalResponseBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create workflow step approval response bad request response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workflow step approval response bad request response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response bad request response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create workflow step approval response bad request response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create workflow step approval response bad request response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create workflow step approval response bad request response
func (o *CreateWorkflowStepApprovalResponseBadRequest) Code() int {
	return 400
}

func (o *CreateWorkflowStepApprovalResponseBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseBadRequest %s", 400, payload)
}

func (o *CreateWorkflowStepApprovalResponseBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseBadRequest %s", 400, payload)
}

func (o *CreateWorkflowStepApprovalResponseBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateWorkflowStepApprovalResponseUnauthorized creates a CreateWorkflowStepApprovalResponseUnauthorized with default headers values
func NewCreateWorkflowStepApprovalResponseUnauthorized() *CreateWorkflowStepApprovalResponseUnauthorized {
	return &CreateWorkflowStepApprovalResponseUnauthorized{}
}

/*
CreateWorkflowStepApprovalResponseUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateWorkflowStepApprovalResponseUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create workflow step approval response unauthorized response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workflow step approval response unauthorized response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response unauthorized response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create workflow step approval response unauthorized response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create workflow step approval response unauthorized response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create workflow step approval response unauthorized response
func (o *CreateWorkflowStepApprovalResponseUnauthorized) Code() int {
	return 401
}

func (o *CreateWorkflowStepApprovalResponseUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseUnauthorized %s", 401, payload)
}

func (o *CreateWorkflowStepApprovalResponseUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseUnauthorized %s", 401, payload)
}

func (o *CreateWorkflowStepApprovalResponseUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateWorkflowStepApprovalResponseForbidden creates a CreateWorkflowStepApprovalResponseForbidden with default headers values
func NewCreateWorkflowStepApprovalResponseForbidden() *CreateWorkflowStepApprovalResponseForbidden {
	return &CreateWorkflowStepApprovalResponseForbidden{}
}

/*
CreateWorkflowStepApprovalResponseForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateWorkflowStepApprovalResponseForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create workflow step approval response forbidden response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workflow step approval response forbidden response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response forbidden response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create workflow step approval response forbidden response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create workflow step approval response forbidden response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create workflow step approval response forbidden response
func (o *CreateWorkflowStepApprovalResponseForbidden) Code() int {
	return 403
}

func (o *CreateWorkflowStepApprovalResponseForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseForbidden %s", 403, payload)
}

func (o *CreateWorkflowStepApprovalResponseForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseForbidden %s", 403, payload)
}

func (o *CreateWorkflowStepApprovalResponseForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateWorkflowStepApprovalResponseNotFound creates a CreateWorkflowStepApprovalResponseNotFound with default headers values
func NewCreateWorkflowStepApprovalResponseNotFound() *CreateWorkflowStepApprovalResponseNotFound {
	return &CreateWorkflowStepApprovalResponseNotFound{}
}

/*
CreateWorkflowStepApprovalResponseNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateWorkflowStepApprovalResponseNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create workflow step approval response not found response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workflow step approval response not found response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response not found response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create workflow step approval response not found response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create workflow step approval response not found response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create workflow step approval response not found response
func (o *CreateWorkflowStepApprovalResponseNotFound) Code() int {
	return 404
}

func (o *CreateWorkflowStepApprovalResponseNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseNotFound %s", 404, payload)
}

func (o *CreateWorkflowStepApprovalResponseNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseNotFound %s", 404, payload)
}

func (o *CreateWorkflowStepApprovalResponseNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateWorkflowStepApprovalResponseInternalServerError creates a CreateWorkflowStepApprovalResponseInternalServerError with default headers values
func NewCreateWorkflowStepApprovalResponseInternalServerError() *CreateWorkflowStepApprovalResponseInternalServerError {
	return &CreateWorkflowStepApprovalResponseInternalServerError{}
}

/*
CreateWorkflowStepApprovalResponseInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateWorkflowStepApprovalResponseInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create workflow step approval response internal server error response has a 2xx status code
func (o *CreateWorkflowStepApprovalResponseInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workflow step approval response internal server error response has a 3xx status code
func (o *CreateWorkflowStepApprovalResponseInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workflow step approval response internal server error response has a 4xx status code
func (o *CreateWorkflowStepApprovalResponseInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create workflow step approval response internal server error response has a 5xx status code
func (o *CreateWorkflowStepApprovalResponseInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create workflow step approval response internal server error response a status code equal to that given
func (o *CreateWorkflowStepApprovalResponseInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create workflow step approval response internal server error response
func (o *CreateWorkflowStepApprovalResponseInternalServerError) Code() int {
	return 500
}

func (o *CreateWorkflowStepApprovalResponseInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseInternalServerError %s", 500, payload)
}

func (o *CreateWorkflowStepApprovalResponseInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/workflows/{workflow_id}/steps/{step_id}/approvals/{approval_id}/response][%d] createWorkflowStepApprovalResponseInternalServerError %s", 500, payload)
}

func (o *CreateWorkflowStepApprovalResponseInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateWorkflowStepApprovalResponseInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
