// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteV1OrgsCurrentReader is a Reader for the DeleteV1OrgsCurrent structure.
type DeleteV1OrgsCurrentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1OrgsCurrentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteV1OrgsCurrentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/orgs/current] DeleteV1OrgsCurrent", response, response.Code())
	}
}

// NewDeleteV1OrgsCurrentOK creates a DeleteV1OrgsCurrentOK with default headers values
func NewDeleteV1OrgsCurrentOK() *DeleteV1OrgsCurrentOK {
	return &DeleteV1OrgsCurrentOK{}
}

/*
DeleteV1OrgsCurrentOK describes a response with status code 200, with default header values.

OK
*/
type DeleteV1OrgsCurrentOK struct {
	Payload bool
}

// IsSuccess returns true when this delete v1 orgs current o k response has a 2xx status code
func (o *DeleteV1OrgsCurrentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 orgs current o k response has a 3xx status code
func (o *DeleteV1OrgsCurrentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 orgs current o k response has a 4xx status code
func (o *DeleteV1OrgsCurrentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 orgs current o k response has a 5xx status code
func (o *DeleteV1OrgsCurrentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 orgs current o k response a status code equal to that given
func (o *DeleteV1OrgsCurrentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete v1 orgs current o k response
func (o *DeleteV1OrgsCurrentOK) Code() int {
	return 200
}

func (o *DeleteV1OrgsCurrentOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/orgs/current][%d] deleteV1OrgsCurrentOK  %+v", 200, o.Payload)
}

func (o *DeleteV1OrgsCurrentOK) String() string {
	return fmt.Sprintf("[DELETE /v1/orgs/current][%d] deleteV1OrgsCurrentOK  %+v", 200, o.Payload)
}

func (o *DeleteV1OrgsCurrentOK) GetPayload() bool {
	return o.Payload
}

func (o *DeleteV1OrgsCurrentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
