// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon-go/models"
)

// NewForceShutDownRunnerParams creates a new ForceShutDownRunnerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewForceShutDownRunnerParams() *ForceShutDownRunnerParams {
	return &ForceShutDownRunnerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewForceShutDownRunnerParamsWithTimeout creates a new ForceShutDownRunnerParams object
// with the ability to set a timeout on a request.
func NewForceShutDownRunnerParamsWithTimeout(timeout time.Duration) *ForceShutDownRunnerParams {
	return &ForceShutDownRunnerParams{
		timeout: timeout,
	}
}

// NewForceShutDownRunnerParamsWithContext creates a new ForceShutDownRunnerParams object
// with the ability to set a context for a request.
func NewForceShutDownRunnerParamsWithContext(ctx context.Context) *ForceShutDownRunnerParams {
	return &ForceShutDownRunnerParams{
		Context: ctx,
	}
}

// NewForceShutDownRunnerParamsWithHTTPClient creates a new ForceShutDownRunnerParams object
// with the ability to set a custom HTTPClient for a request.
func NewForceShutDownRunnerParamsWithHTTPClient(client *http.Client) *ForceShutDownRunnerParams {
	return &ForceShutDownRunnerParams{
		HTTPClient: client,
	}
}

/*
ForceShutDownRunnerParams contains all the parameters to send to the API endpoint

	for the force shut down runner operation.

	Typically these are written to a http.Request.
*/
type ForceShutDownRunnerParams struct {

	/* Req.

	   Input
	*/
	Req models.ServiceForceShutdownRequest

	/* RunnerID.

	   runner ID
	*/
	RunnerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the force shut down runner params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ForceShutDownRunnerParams) WithDefaults() *ForceShutDownRunnerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the force shut down runner params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ForceShutDownRunnerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the force shut down runner params
func (o *ForceShutDownRunnerParams) WithTimeout(timeout time.Duration) *ForceShutDownRunnerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the force shut down runner params
func (o *ForceShutDownRunnerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the force shut down runner params
func (o *ForceShutDownRunnerParams) WithContext(ctx context.Context) *ForceShutDownRunnerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the force shut down runner params
func (o *ForceShutDownRunnerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the force shut down runner params
func (o *ForceShutDownRunnerParams) WithHTTPClient(client *http.Client) *ForceShutDownRunnerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the force shut down runner params
func (o *ForceShutDownRunnerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the force shut down runner params
func (o *ForceShutDownRunnerParams) WithReq(req models.ServiceForceShutdownRequest) *ForceShutDownRunnerParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the force shut down runner params
func (o *ForceShutDownRunnerParams) SetReq(req models.ServiceForceShutdownRequest) {
	o.Req = req
}

// WithRunnerID adds the runnerID to the force shut down runner params
func (o *ForceShutDownRunnerParams) WithRunnerID(runnerID string) *ForceShutDownRunnerParams {
	o.SetRunnerID(runnerID)
	return o
}

// SetRunnerID adds the runnerId to the force shut down runner params
func (o *ForceShutDownRunnerParams) SetRunnerID(runnerID string) {
	o.RunnerID = runnerID
}

// WriteToRequest writes these params to a swagger request
func (o *ForceShutDownRunnerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	// path param runner_id
	if err := r.SetPathParam("runner_id", o.RunnerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
