// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInstallDeploysParams creates a new GetInstallDeploysParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstallDeploysParams() *GetInstallDeploysParams {
	return &GetInstallDeploysParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstallDeploysParamsWithTimeout creates a new GetInstallDeploysParams object
// with the ability to set a timeout on a request.
func NewGetInstallDeploysParamsWithTimeout(timeout time.Duration) *GetInstallDeploysParams {
	return &GetInstallDeploysParams{
		timeout: timeout,
	}
}

// NewGetInstallDeploysParamsWithContext creates a new GetInstallDeploysParams object
// with the ability to set a context for a request.
func NewGetInstallDeploysParamsWithContext(ctx context.Context) *GetInstallDeploysParams {
	return &GetInstallDeploysParams{
		Context: ctx,
	}
}

// NewGetInstallDeploysParamsWithHTTPClient creates a new GetInstallDeploysParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstallDeploysParamsWithHTTPClient(client *http.Client) *GetInstallDeploysParams {
	return &GetInstallDeploysParams{
		HTTPClient: client,
	}
}

/*
GetInstallDeploysParams contains all the parameters to send to the API endpoint

	for the get install deploys operation.

	Typically these are written to a http.Request.
*/
type GetInstallDeploysParams struct {

	/* InstallID.

	   install ID
	*/
	InstallID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get install deploys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallDeploysParams) WithDefaults() *GetInstallDeploysParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get install deploys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallDeploysParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get install deploys params
func (o *GetInstallDeploysParams) WithTimeout(timeout time.Duration) *GetInstallDeploysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get install deploys params
func (o *GetInstallDeploysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get install deploys params
func (o *GetInstallDeploysParams) WithContext(ctx context.Context) *GetInstallDeploysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get install deploys params
func (o *GetInstallDeploysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get install deploys params
func (o *GetInstallDeploysParams) WithHTTPClient(client *http.Client) *GetInstallDeploysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get install deploys params
func (o *GetInstallDeploysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the get install deploys params
func (o *GetInstallDeploysParams) WithInstallID(installID string) *GetInstallDeploysParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the get install deploys params
func (o *GetInstallDeploysParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstallDeploysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
