// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon-go/models"
)

// GetInstallWorkflowsReader is a Reader for the GetInstallWorkflows structure.
type GetInstallWorkflowsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInstallWorkflowsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInstallWorkflowsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetInstallWorkflowsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetInstallWorkflowsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetInstallWorkflowsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetInstallWorkflowsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetInstallWorkflowsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/installs/{install_id}/workflows] GetInstallWorkflows", response, response.Code())
	}
}

// NewGetInstallWorkflowsOK creates a GetInstallWorkflowsOK with default headers values
func NewGetInstallWorkflowsOK() *GetInstallWorkflowsOK {
	return &GetInstallWorkflowsOK{}
}

/*
GetInstallWorkflowsOK describes a response with status code 200, with default header values.

OK
*/
type GetInstallWorkflowsOK struct {
	Payload []*models.AppInstallSandboxRun
}

// IsSuccess returns true when this get install workflows o k response has a 2xx status code
func (o *GetInstallWorkflowsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get install workflows o k response has a 3xx status code
func (o *GetInstallWorkflowsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install workflows o k response has a 4xx status code
func (o *GetInstallWorkflowsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get install workflows o k response has a 5xx status code
func (o *GetInstallWorkflowsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get install workflows o k response a status code equal to that given
func (o *GetInstallWorkflowsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get install workflows o k response
func (o *GetInstallWorkflowsOK) Code() int {
	return 200
}

func (o *GetInstallWorkflowsOK) Error() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsOK  %+v", 200, o.Payload)
}

func (o *GetInstallWorkflowsOK) String() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsOK  %+v", 200, o.Payload)
}

func (o *GetInstallWorkflowsOK) GetPayload() []*models.AppInstallSandboxRun {
	return o.Payload
}

func (o *GetInstallWorkflowsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstallWorkflowsBadRequest creates a GetInstallWorkflowsBadRequest with default headers values
func NewGetInstallWorkflowsBadRequest() *GetInstallWorkflowsBadRequest {
	return &GetInstallWorkflowsBadRequest{}
}

/*
GetInstallWorkflowsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetInstallWorkflowsBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install workflows bad request response has a 2xx status code
func (o *GetInstallWorkflowsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install workflows bad request response has a 3xx status code
func (o *GetInstallWorkflowsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install workflows bad request response has a 4xx status code
func (o *GetInstallWorkflowsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install workflows bad request response has a 5xx status code
func (o *GetInstallWorkflowsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get install workflows bad request response a status code equal to that given
func (o *GetInstallWorkflowsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get install workflows bad request response
func (o *GetInstallWorkflowsBadRequest) Code() int {
	return 400
}

func (o *GetInstallWorkflowsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsBadRequest  %+v", 400, o.Payload)
}

func (o *GetInstallWorkflowsBadRequest) String() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsBadRequest  %+v", 400, o.Payload)
}

func (o *GetInstallWorkflowsBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallWorkflowsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstallWorkflowsUnauthorized creates a GetInstallWorkflowsUnauthorized with default headers values
func NewGetInstallWorkflowsUnauthorized() *GetInstallWorkflowsUnauthorized {
	return &GetInstallWorkflowsUnauthorized{}
}

/*
GetInstallWorkflowsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetInstallWorkflowsUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install workflows unauthorized response has a 2xx status code
func (o *GetInstallWorkflowsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install workflows unauthorized response has a 3xx status code
func (o *GetInstallWorkflowsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install workflows unauthorized response has a 4xx status code
func (o *GetInstallWorkflowsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install workflows unauthorized response has a 5xx status code
func (o *GetInstallWorkflowsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get install workflows unauthorized response a status code equal to that given
func (o *GetInstallWorkflowsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get install workflows unauthorized response
func (o *GetInstallWorkflowsUnauthorized) Code() int {
	return 401
}

func (o *GetInstallWorkflowsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetInstallWorkflowsUnauthorized) String() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetInstallWorkflowsUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallWorkflowsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstallWorkflowsForbidden creates a GetInstallWorkflowsForbidden with default headers values
func NewGetInstallWorkflowsForbidden() *GetInstallWorkflowsForbidden {
	return &GetInstallWorkflowsForbidden{}
}

/*
GetInstallWorkflowsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetInstallWorkflowsForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install workflows forbidden response has a 2xx status code
func (o *GetInstallWorkflowsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install workflows forbidden response has a 3xx status code
func (o *GetInstallWorkflowsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install workflows forbidden response has a 4xx status code
func (o *GetInstallWorkflowsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install workflows forbidden response has a 5xx status code
func (o *GetInstallWorkflowsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get install workflows forbidden response a status code equal to that given
func (o *GetInstallWorkflowsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get install workflows forbidden response
func (o *GetInstallWorkflowsForbidden) Code() int {
	return 403
}

func (o *GetInstallWorkflowsForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsForbidden  %+v", 403, o.Payload)
}

func (o *GetInstallWorkflowsForbidden) String() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsForbidden  %+v", 403, o.Payload)
}

func (o *GetInstallWorkflowsForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallWorkflowsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstallWorkflowsNotFound creates a GetInstallWorkflowsNotFound with default headers values
func NewGetInstallWorkflowsNotFound() *GetInstallWorkflowsNotFound {
	return &GetInstallWorkflowsNotFound{}
}

/*
GetInstallWorkflowsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetInstallWorkflowsNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install workflows not found response has a 2xx status code
func (o *GetInstallWorkflowsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install workflows not found response has a 3xx status code
func (o *GetInstallWorkflowsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install workflows not found response has a 4xx status code
func (o *GetInstallWorkflowsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get install workflows not found response has a 5xx status code
func (o *GetInstallWorkflowsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get install workflows not found response a status code equal to that given
func (o *GetInstallWorkflowsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get install workflows not found response
func (o *GetInstallWorkflowsNotFound) Code() int {
	return 404
}

func (o *GetInstallWorkflowsNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsNotFound  %+v", 404, o.Payload)
}

func (o *GetInstallWorkflowsNotFound) String() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsNotFound  %+v", 404, o.Payload)
}

func (o *GetInstallWorkflowsNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallWorkflowsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstallWorkflowsInternalServerError creates a GetInstallWorkflowsInternalServerError with default headers values
func NewGetInstallWorkflowsInternalServerError() *GetInstallWorkflowsInternalServerError {
	return &GetInstallWorkflowsInternalServerError{}
}

/*
GetInstallWorkflowsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetInstallWorkflowsInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get install workflows internal server error response has a 2xx status code
func (o *GetInstallWorkflowsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get install workflows internal server error response has a 3xx status code
func (o *GetInstallWorkflowsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get install workflows internal server error response has a 4xx status code
func (o *GetInstallWorkflowsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get install workflows internal server error response has a 5xx status code
func (o *GetInstallWorkflowsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get install workflows internal server error response a status code equal to that given
func (o *GetInstallWorkflowsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get install workflows internal server error response
func (o *GetInstallWorkflowsInternalServerError) Code() int {
	return 500
}

func (o *GetInstallWorkflowsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInstallWorkflowsInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/workflows][%d] getInstallWorkflowsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInstallWorkflowsInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetInstallWorkflowsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
