// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon-go/models"
)

// GetAppSandboxConfigsReader is a Reader for the GetAppSandboxConfigs structure.
type GetAppSandboxConfigsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAppSandboxConfigsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAppSandboxConfigsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAppSandboxConfigsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAppSandboxConfigsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAppSandboxConfigsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAppSandboxConfigsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAppSandboxConfigsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/apps/{app_id}/sandbox-configs] GetAppSandboxConfigs", response, response.Code())
	}
}

// NewGetAppSandboxConfigsOK creates a GetAppSandboxConfigsOK with default headers values
func NewGetAppSandboxConfigsOK() *GetAppSandboxConfigsOK {
	return &GetAppSandboxConfigsOK{}
}

/*
GetAppSandboxConfigsOK describes a response with status code 200, with default header values.

OK
*/
type GetAppSandboxConfigsOK struct {
	Payload []*models.AppAppSandboxConfig
}

// IsSuccess returns true when this get app sandbox configs o k response has a 2xx status code
func (o *GetAppSandboxConfigsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get app sandbox configs o k response has a 3xx status code
func (o *GetAppSandboxConfigsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app sandbox configs o k response has a 4xx status code
func (o *GetAppSandboxConfigsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get app sandbox configs o k response has a 5xx status code
func (o *GetAppSandboxConfigsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get app sandbox configs o k response a status code equal to that given
func (o *GetAppSandboxConfigsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get app sandbox configs o k response
func (o *GetAppSandboxConfigsOK) Code() int {
	return 200
}

func (o *GetAppSandboxConfigsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsOK %s", 200, payload)
}

func (o *GetAppSandboxConfigsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsOK %s", 200, payload)
}

func (o *GetAppSandboxConfigsOK) GetPayload() []*models.AppAppSandboxConfig {
	return o.Payload
}

func (o *GetAppSandboxConfigsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppSandboxConfigsBadRequest creates a GetAppSandboxConfigsBadRequest with default headers values
func NewGetAppSandboxConfigsBadRequest() *GetAppSandboxConfigsBadRequest {
	return &GetAppSandboxConfigsBadRequest{}
}

/*
GetAppSandboxConfigsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAppSandboxConfigsBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get app sandbox configs bad request response has a 2xx status code
func (o *GetAppSandboxConfigsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get app sandbox configs bad request response has a 3xx status code
func (o *GetAppSandboxConfigsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app sandbox configs bad request response has a 4xx status code
func (o *GetAppSandboxConfigsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get app sandbox configs bad request response has a 5xx status code
func (o *GetAppSandboxConfigsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get app sandbox configs bad request response a status code equal to that given
func (o *GetAppSandboxConfigsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get app sandbox configs bad request response
func (o *GetAppSandboxConfigsBadRequest) Code() int {
	return 400
}

func (o *GetAppSandboxConfigsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsBadRequest %s", 400, payload)
}

func (o *GetAppSandboxConfigsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsBadRequest %s", 400, payload)
}

func (o *GetAppSandboxConfigsBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAppSandboxConfigsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppSandboxConfigsUnauthorized creates a GetAppSandboxConfigsUnauthorized with default headers values
func NewGetAppSandboxConfigsUnauthorized() *GetAppSandboxConfigsUnauthorized {
	return &GetAppSandboxConfigsUnauthorized{}
}

/*
GetAppSandboxConfigsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAppSandboxConfigsUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get app sandbox configs unauthorized response has a 2xx status code
func (o *GetAppSandboxConfigsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get app sandbox configs unauthorized response has a 3xx status code
func (o *GetAppSandboxConfigsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app sandbox configs unauthorized response has a 4xx status code
func (o *GetAppSandboxConfigsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get app sandbox configs unauthorized response has a 5xx status code
func (o *GetAppSandboxConfigsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get app sandbox configs unauthorized response a status code equal to that given
func (o *GetAppSandboxConfigsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get app sandbox configs unauthorized response
func (o *GetAppSandboxConfigsUnauthorized) Code() int {
	return 401
}

func (o *GetAppSandboxConfigsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsUnauthorized %s", 401, payload)
}

func (o *GetAppSandboxConfigsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsUnauthorized %s", 401, payload)
}

func (o *GetAppSandboxConfigsUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAppSandboxConfigsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppSandboxConfigsForbidden creates a GetAppSandboxConfigsForbidden with default headers values
func NewGetAppSandboxConfigsForbidden() *GetAppSandboxConfigsForbidden {
	return &GetAppSandboxConfigsForbidden{}
}

/*
GetAppSandboxConfigsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAppSandboxConfigsForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get app sandbox configs forbidden response has a 2xx status code
func (o *GetAppSandboxConfigsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get app sandbox configs forbidden response has a 3xx status code
func (o *GetAppSandboxConfigsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app sandbox configs forbidden response has a 4xx status code
func (o *GetAppSandboxConfigsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get app sandbox configs forbidden response has a 5xx status code
func (o *GetAppSandboxConfigsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get app sandbox configs forbidden response a status code equal to that given
func (o *GetAppSandboxConfigsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get app sandbox configs forbidden response
func (o *GetAppSandboxConfigsForbidden) Code() int {
	return 403
}

func (o *GetAppSandboxConfigsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsForbidden %s", 403, payload)
}

func (o *GetAppSandboxConfigsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsForbidden %s", 403, payload)
}

func (o *GetAppSandboxConfigsForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAppSandboxConfigsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppSandboxConfigsNotFound creates a GetAppSandboxConfigsNotFound with default headers values
func NewGetAppSandboxConfigsNotFound() *GetAppSandboxConfigsNotFound {
	return &GetAppSandboxConfigsNotFound{}
}

/*
GetAppSandboxConfigsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAppSandboxConfigsNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get app sandbox configs not found response has a 2xx status code
func (o *GetAppSandboxConfigsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get app sandbox configs not found response has a 3xx status code
func (o *GetAppSandboxConfigsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app sandbox configs not found response has a 4xx status code
func (o *GetAppSandboxConfigsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get app sandbox configs not found response has a 5xx status code
func (o *GetAppSandboxConfigsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get app sandbox configs not found response a status code equal to that given
func (o *GetAppSandboxConfigsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get app sandbox configs not found response
func (o *GetAppSandboxConfigsNotFound) Code() int {
	return 404
}

func (o *GetAppSandboxConfigsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsNotFound %s", 404, payload)
}

func (o *GetAppSandboxConfigsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsNotFound %s", 404, payload)
}

func (o *GetAppSandboxConfigsNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAppSandboxConfigsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppSandboxConfigsInternalServerError creates a GetAppSandboxConfigsInternalServerError with default headers values
func NewGetAppSandboxConfigsInternalServerError() *GetAppSandboxConfigsInternalServerError {
	return &GetAppSandboxConfigsInternalServerError{}
}

/*
GetAppSandboxConfigsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAppSandboxConfigsInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get app sandbox configs internal server error response has a 2xx status code
func (o *GetAppSandboxConfigsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get app sandbox configs internal server error response has a 3xx status code
func (o *GetAppSandboxConfigsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app sandbox configs internal server error response has a 4xx status code
func (o *GetAppSandboxConfigsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get app sandbox configs internal server error response has a 5xx status code
func (o *GetAppSandboxConfigsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get app sandbox configs internal server error response a status code equal to that given
func (o *GetAppSandboxConfigsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get app sandbox configs internal server error response
func (o *GetAppSandboxConfigsInternalServerError) Code() int {
	return 500
}

func (o *GetAppSandboxConfigsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsInternalServerError %s", 500, payload)
}

func (o *GetAppSandboxConfigsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/sandbox-configs][%d] getAppSandboxConfigsInternalServerError %s", 500, payload)
}

func (o *GetAppSandboxConfigsInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAppSandboxConfigsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
