// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInstallStateParams creates a new GetInstallStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstallStateParams() *GetInstallStateParams {
	return &GetInstallStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstallStateParamsWithTimeout creates a new GetInstallStateParams object
// with the ability to set a timeout on a request.
func NewGetInstallStateParamsWithTimeout(timeout time.Duration) *GetInstallStateParams {
	return &GetInstallStateParams{
		timeout: timeout,
	}
}

// NewGetInstallStateParamsWithContext creates a new GetInstallStateParams object
// with the ability to set a context for a request.
func NewGetInstallStateParamsWithContext(ctx context.Context) *GetInstallStateParams {
	return &GetInstallStateParams{
		Context: ctx,
	}
}

// NewGetInstallStateParamsWithHTTPClient creates a new GetInstallStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstallStateParamsWithHTTPClient(client *http.Client) *GetInstallStateParams {
	return &GetInstallStateParams{
		HTTPClient: client,
	}
}

/*
GetInstallStateParams contains all the parameters to send to the API endpoint

	for the get install state operation.

	Typically these are written to a http.Request.
*/
type GetInstallStateParams struct {

	/* InstallID.

	   install ID
	*/
	InstallID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get install state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallStateParams) WithDefaults() *GetInstallStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get install state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get install state params
func (o *GetInstallStateParams) WithTimeout(timeout time.Duration) *GetInstallStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get install state params
func (o *GetInstallStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get install state params
func (o *GetInstallStateParams) WithContext(ctx context.Context) *GetInstallStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get install state params
func (o *GetInstallStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get install state params
func (o *GetInstallStateParams) WithHTTPClient(client *http.Client) *GetInstallStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get install state params
func (o *GetInstallStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the get install state params
func (o *GetInstallStateParams) WithInstallID(installID string) *GetInstallStateParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the get install state params
func (o *GetInstallStateParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstallStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
