// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon-go/models"
)

// GetComponentDependentsReader is a Reader for the GetComponentDependents structure.
type GetComponentDependentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetComponentDependentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetComponentDependentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetComponentDependentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetComponentDependentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetComponentDependentsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetComponentDependentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetComponentDependentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/components/{component_id}/dependents] GetComponentDependents", response, response.Code())
	}
}

// NewGetComponentDependentsOK creates a GetComponentDependentsOK with default headers values
func NewGetComponentDependentsOK() *GetComponentDependentsOK {
	return &GetComponentDependentsOK{}
}

/*
GetComponentDependentsOK describes a response with status code 200, with default header values.

OK
*/
type GetComponentDependentsOK struct {
	Payload *models.ServiceComponentChildren
}

// IsSuccess returns true when this get component dependents o k response has a 2xx status code
func (o *GetComponentDependentsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get component dependents o k response has a 3xx status code
func (o *GetComponentDependentsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get component dependents o k response has a 4xx status code
func (o *GetComponentDependentsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get component dependents o k response has a 5xx status code
func (o *GetComponentDependentsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get component dependents o k response a status code equal to that given
func (o *GetComponentDependentsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get component dependents o k response
func (o *GetComponentDependentsOK) Code() int {
	return 200
}

func (o *GetComponentDependentsOK) Error() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsOK  %+v", 200, o.Payload)
}

func (o *GetComponentDependentsOK) String() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsOK  %+v", 200, o.Payload)
}

func (o *GetComponentDependentsOK) GetPayload() *models.ServiceComponentChildren {
	return o.Payload
}

func (o *GetComponentDependentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceComponentChildren)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentDependentsBadRequest creates a GetComponentDependentsBadRequest with default headers values
func NewGetComponentDependentsBadRequest() *GetComponentDependentsBadRequest {
	return &GetComponentDependentsBadRequest{}
}

/*
GetComponentDependentsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetComponentDependentsBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get component dependents bad request response has a 2xx status code
func (o *GetComponentDependentsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get component dependents bad request response has a 3xx status code
func (o *GetComponentDependentsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get component dependents bad request response has a 4xx status code
func (o *GetComponentDependentsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get component dependents bad request response has a 5xx status code
func (o *GetComponentDependentsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get component dependents bad request response a status code equal to that given
func (o *GetComponentDependentsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get component dependents bad request response
func (o *GetComponentDependentsBadRequest) Code() int {
	return 400
}

func (o *GetComponentDependentsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsBadRequest  %+v", 400, o.Payload)
}

func (o *GetComponentDependentsBadRequest) String() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsBadRequest  %+v", 400, o.Payload)
}

func (o *GetComponentDependentsBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetComponentDependentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentDependentsUnauthorized creates a GetComponentDependentsUnauthorized with default headers values
func NewGetComponentDependentsUnauthorized() *GetComponentDependentsUnauthorized {
	return &GetComponentDependentsUnauthorized{}
}

/*
GetComponentDependentsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetComponentDependentsUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get component dependents unauthorized response has a 2xx status code
func (o *GetComponentDependentsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get component dependents unauthorized response has a 3xx status code
func (o *GetComponentDependentsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get component dependents unauthorized response has a 4xx status code
func (o *GetComponentDependentsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get component dependents unauthorized response has a 5xx status code
func (o *GetComponentDependentsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get component dependents unauthorized response a status code equal to that given
func (o *GetComponentDependentsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get component dependents unauthorized response
func (o *GetComponentDependentsUnauthorized) Code() int {
	return 401
}

func (o *GetComponentDependentsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetComponentDependentsUnauthorized) String() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetComponentDependentsUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetComponentDependentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentDependentsForbidden creates a GetComponentDependentsForbidden with default headers values
func NewGetComponentDependentsForbidden() *GetComponentDependentsForbidden {
	return &GetComponentDependentsForbidden{}
}

/*
GetComponentDependentsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetComponentDependentsForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get component dependents forbidden response has a 2xx status code
func (o *GetComponentDependentsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get component dependents forbidden response has a 3xx status code
func (o *GetComponentDependentsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get component dependents forbidden response has a 4xx status code
func (o *GetComponentDependentsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get component dependents forbidden response has a 5xx status code
func (o *GetComponentDependentsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get component dependents forbidden response a status code equal to that given
func (o *GetComponentDependentsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get component dependents forbidden response
func (o *GetComponentDependentsForbidden) Code() int {
	return 403
}

func (o *GetComponentDependentsForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsForbidden  %+v", 403, o.Payload)
}

func (o *GetComponentDependentsForbidden) String() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsForbidden  %+v", 403, o.Payload)
}

func (o *GetComponentDependentsForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetComponentDependentsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentDependentsNotFound creates a GetComponentDependentsNotFound with default headers values
func NewGetComponentDependentsNotFound() *GetComponentDependentsNotFound {
	return &GetComponentDependentsNotFound{}
}

/*
GetComponentDependentsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetComponentDependentsNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get component dependents not found response has a 2xx status code
func (o *GetComponentDependentsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get component dependents not found response has a 3xx status code
func (o *GetComponentDependentsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get component dependents not found response has a 4xx status code
func (o *GetComponentDependentsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get component dependents not found response has a 5xx status code
func (o *GetComponentDependentsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get component dependents not found response a status code equal to that given
func (o *GetComponentDependentsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get component dependents not found response
func (o *GetComponentDependentsNotFound) Code() int {
	return 404
}

func (o *GetComponentDependentsNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsNotFound  %+v", 404, o.Payload)
}

func (o *GetComponentDependentsNotFound) String() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsNotFound  %+v", 404, o.Payload)
}

func (o *GetComponentDependentsNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetComponentDependentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentDependentsInternalServerError creates a GetComponentDependentsInternalServerError with default headers values
func NewGetComponentDependentsInternalServerError() *GetComponentDependentsInternalServerError {
	return &GetComponentDependentsInternalServerError{}
}

/*
GetComponentDependentsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetComponentDependentsInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get component dependents internal server error response has a 2xx status code
func (o *GetComponentDependentsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get component dependents internal server error response has a 3xx status code
func (o *GetComponentDependentsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get component dependents internal server error response has a 4xx status code
func (o *GetComponentDependentsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get component dependents internal server error response has a 5xx status code
func (o *GetComponentDependentsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get component dependents internal server error response a status code equal to that given
func (o *GetComponentDependentsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get component dependents internal server error response
func (o *GetComponentDependentsInternalServerError) Code() int {
	return 500
}

func (o *GetComponentDependentsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetComponentDependentsInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/components/{component_id}/dependents][%d] getComponentDependentsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetComponentDependentsInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetComponentDependentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
