// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInstallerInstallParams creates a new GetInstallerInstallParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstallerInstallParams() *GetInstallerInstallParams {
	return &GetInstallerInstallParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstallerInstallParamsWithTimeout creates a new GetInstallerInstallParams object
// with the ability to set a timeout on a request.
func NewGetInstallerInstallParamsWithTimeout(timeout time.Duration) *GetInstallerInstallParams {
	return &GetInstallerInstallParams{
		timeout: timeout,
	}
}

// NewGetInstallerInstallParamsWithContext creates a new GetInstallerInstallParams object
// with the ability to set a context for a request.
func NewGetInstallerInstallParamsWithContext(ctx context.Context) *GetInstallerInstallParams {
	return &GetInstallerInstallParams{
		Context: ctx,
	}
}

// NewGetInstallerInstallParamsWithHTTPClient creates a new GetInstallerInstallParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstallerInstallParamsWithHTTPClient(client *http.Client) *GetInstallerInstallParams {
	return &GetInstallerInstallParams{
		HTTPClient: client,
	}
}

/*
GetInstallerInstallParams contains all the parameters to send to the API endpoint

	for the get installer install operation.

	Typically these are written to a http.Request.
*/
type GetInstallerInstallParams struct {

	/* InstallID.

	   install id
	*/
	InstallID string

	/* InstallerSlug.

	   installer slug or ID
	*/
	InstallerSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get installer install params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallerInstallParams) WithDefaults() *GetInstallerInstallParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get installer install params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallerInstallParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get installer install params
func (o *GetInstallerInstallParams) WithTimeout(timeout time.Duration) *GetInstallerInstallParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get installer install params
func (o *GetInstallerInstallParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get installer install params
func (o *GetInstallerInstallParams) WithContext(ctx context.Context) *GetInstallerInstallParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get installer install params
func (o *GetInstallerInstallParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get installer install params
func (o *GetInstallerInstallParams) WithHTTPClient(client *http.Client) *GetInstallerInstallParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get installer install params
func (o *GetInstallerInstallParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the get installer install params
func (o *GetInstallerInstallParams) WithInstallID(installID string) *GetInstallerInstallParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the get installer install params
func (o *GetInstallerInstallParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WithInstallerSlug adds the installerSlug to the get installer install params
func (o *GetInstallerInstallParams) WithInstallerSlug(installerSlug string) *GetInstallerInstallParams {
	o.SetInstallerSlug(installerSlug)
	return o
}

// SetInstallerSlug adds the installerSlug to the get installer install params
func (o *GetInstallerInstallParams) SetInstallerSlug(installerSlug string) {
	o.InstallerSlug = installerSlug
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstallerInstallParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	// path param installer_slug
	if err := r.SetPathParam("installer_slug", o.InstallerSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
