// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon-go/models"
)

// GetV1InstallsInstallIDDeploysReader is a Reader for the GetV1InstallsInstallIDDeploys structure.
type GetV1InstallsInstallIDDeploysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1InstallsInstallIDDeploysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1InstallsInstallIDDeploysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/installs/{install_id}/deploys] GetV1InstallsInstallIDDeploys", response, response.Code())
	}
}

// NewGetV1InstallsInstallIDDeploysOK creates a GetV1InstallsInstallIDDeploysOK with default headers values
func NewGetV1InstallsInstallIDDeploysOK() *GetV1InstallsInstallIDDeploysOK {
	return &GetV1InstallsInstallIDDeploysOK{}
}

/*
GetV1InstallsInstallIDDeploysOK describes a response with status code 200, with default header values.

OK
*/
type GetV1InstallsInstallIDDeploysOK struct {
	Payload []*models.AppInstallDeploy
}

// IsSuccess returns true when this get v1 installs install Id deploys o k response has a 2xx status code
func (o *GetV1InstallsInstallIDDeploysOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 installs install Id deploys o k response has a 3xx status code
func (o *GetV1InstallsInstallIDDeploysOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 installs install Id deploys o k response has a 4xx status code
func (o *GetV1InstallsInstallIDDeploysOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 installs install Id deploys o k response has a 5xx status code
func (o *GetV1InstallsInstallIDDeploysOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 installs install Id deploys o k response a status code equal to that given
func (o *GetV1InstallsInstallIDDeploysOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 installs install Id deploys o k response
func (o *GetV1InstallsInstallIDDeploysOK) Code() int {
	return 200
}

func (o *GetV1InstallsInstallIDDeploysOK) Error() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/deploys][%d] getV1InstallsInstallIdDeploysOK  %+v", 200, o.Payload)
}

func (o *GetV1InstallsInstallIDDeploysOK) String() string {
	return fmt.Sprintf("[GET /v1/installs/{install_id}/deploys][%d] getV1InstallsInstallIdDeploysOK  %+v", 200, o.Payload)
}

func (o *GetV1InstallsInstallIDDeploysOK) GetPayload() []*models.AppInstallDeploy {
	return o.Payload
}

func (o *GetV1InstallsInstallIDDeploysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
