// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHandleWebhookParams creates a new HandleWebhookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHandleWebhookParams() *HandleWebhookParams {
	return &HandleWebhookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHandleWebhookParamsWithTimeout creates a new HandleWebhookParams object
// with the ability to set a timeout on a request.
func NewHandleWebhookParamsWithTimeout(timeout time.Duration) *HandleWebhookParams {
	return &HandleWebhookParams{
		timeout: timeout,
	}
}

// NewHandleWebhookParamsWithContext creates a new HandleWebhookParams object
// with the ability to set a context for a request.
func NewHandleWebhookParamsWithContext(ctx context.Context) *HandleWebhookParams {
	return &HandleWebhookParams{
		Context: ctx,
	}
}

// NewHandleWebhookParamsWithHTTPClient creates a new HandleWebhookParams object
// with the ability to set a custom HTTPClient for a request.
func NewHandleWebhookParamsWithHTTPClient(client *http.Client) *HandleWebhookParams {
	return &HandleWebhookParams{
		HTTPClient: client,
	}
}

/*
HandleWebhookParams contains all the parameters to send to the API endpoint

	for the handle webhook operation.

	Typically these are written to a http.Request.
*/
type HandleWebhookParams struct {

	/* Req.

	   Input
	*/
	Req interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the handle webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HandleWebhookParams) WithDefaults() *HandleWebhookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the handle webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HandleWebhookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the handle webhook params
func (o *HandleWebhookParams) WithTimeout(timeout time.Duration) *HandleWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the handle webhook params
func (o *HandleWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the handle webhook params
func (o *HandleWebhookParams) WithContext(ctx context.Context) *HandleWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the handle webhook params
func (o *HandleWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the handle webhook params
func (o *HandleWebhookParams) WithHTTPClient(client *http.Client) *HandleWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the handle webhook params
func (o *HandleWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the handle webhook params
func (o *HandleWebhookParams) WithReq(req interface{}) *HandleWebhookParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the handle webhook params
func (o *HandleWebhookParams) SetReq(req interface{}) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *HandleWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
