name: 'Stale Pull Requests and Issues'
on:
  schedule:
    - cron: '50 * * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 2 days.'
          stale-pr-message: 'This PR was marked as stale, and will be closed after 3 more days. Add the #keep-open label to prevent this from being closed.'
          close-pr-message: 'This PR was closed because it has been stalled for 5 days with no activity.'
          days-before-stale: 2
          days-before-close: 5

          stale-pr-label: stale
          close-pr-label: closed-by-stale-action
          stale-issue-label: stale
          exempt-pr-labels: keep-open
          operations-per-run: 100
          ignore-updates: true
          debug-only:  false# Temporarily enable this to see what's happening
