// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppHelmConfig app helm config
//
// swagger:model app.HelmConfig
type AppHelmConfig struct {

	// chart name
	ChartName string `json:"chart_name,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// storage driver
	StorageDriver string `json:"storage_driver,omitempty"`

	// Newer fields that we don't need to store as columns in the database
	TakeOwnership bool `json:"take_ownership,omitempty"`

	// values
	Values map[string]string `json:"values,omitempty"`

	// values files
	ValuesFiles []string `json:"values_files"`
}

// Validate validates this app helm config
func (m *AppHelmConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app helm config based on context it is used
func (m *AppHelmConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppHelmConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppHelmConfig) UnmarshalBinary(b []byte) error {
	var res AppHelmConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
