// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppAWSStackOutputs app a w s stack outputs
//
// swagger:model app.AWSStackOutputs
type AppAWSStackOutputs struct {

	// account id
	AccountID string `json:"account_id,omitempty"`

	// deprovision iam role arn
	DeprovisionIamRoleArn string `json:"deprovision_iam_role_arn,omitempty"`

	// maintenance iam role arn
	MaintenanceIamRoleArn string `json:"maintenance_iam_role_arn,omitempty"`

	// private subnets
	PrivateSubnets []string `json:"private_subnets"`

	// provision iam role arn
	ProvisionIamRoleArn string `json:"provision_iam_role_arn,omitempty"`

	// public subnets
	PublicSubnets []string `json:"public_subnets"`

	// region
	Region string `json:"region,omitempty"`

	// runner iam role arn
	RunnerIamRoleArn string `json:"runner_iam_role_arn,omitempty"`

	// runner subnet
	RunnerSubnet string `json:"runner_subnet,omitempty"`

	// vpc id
	VpcID string `json:"vpc_id,omitempty"`
}

// Validate validates this app a w s stack outputs
func (m *AppAWSStackOutputs) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app a w s stack outputs based on context it is used
func (m *AppAWSStackOutputs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppAWSStackOutputs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppAWSStackOutputs) UnmarshalBinary(b []byte) error {
	var res AppAWSStackOutputs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
