// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceCreateAppConfigRequest service create app config request
//
// swagger:model service.CreateAppConfigRequest
type ServiceCreateAppConfigRequest struct {

	// cli version
	CliVersion string `json:"cli_version,omitempty"`

	// not required Readme
	Readme string `json:"readme,omitempty"`
}

// Validate validates this service create app config request
func (m *ServiceCreateAppConfigRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service create app config request based on context it is used
func (m *ServiceCreateAppConfigRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceCreateAppConfigRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceCreateAppConfigRequest) UnmarshalBinary(b []byte) error {
	var res ServiceCreateAppConfigRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
