// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceCreateAppBranchRequest service create app branch request
//
// swagger:model service.CreateAppBranchRequest
type ServiceCreateAppBranchRequest struct {

	// vcs connection branch id
	VcsConnectionBranchID string `json:"vcs_connection_branch_id,omitempty"`
}

// Validate validates this service create app branch request
func (m *ServiceCreateAppBranchRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service create app branch request based on context it is used
func (m *ServiceCreateAppBranchRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceCreateAppBranchRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceCreateAppBranchRequest) UnmarshalBinary(b []byte) error {
	var res ServiceCreateAppBranchRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
